### PR TITLE
Update core and web modules to 4.3.2

### PR DESCRIPTION
**Pull request by nonsleepr**
# Proposed Changes

- Upgrade core Pi-Hole to 4.3.2
- Upgrade Pi-Hole UI to 4.3.2
- Upgrade base image version to 5.0.3

Tested by building and running as a local extension for HA 0.102.3.

## Related Issues

- #106 
- #107

### CODE REVIEW

**Comment by frenck** [comment]
We don't combine multiple upgrades in a single commit.

Nevertheless, thank you for your contribution.

**Comment by nonsleepr** [comment]
Well, that's harsh. Mind describing the requirements for the commits in `CONTRIBUTING.md`?

**Comment by frenck** [comment]
Sorry, I don't mean to be harsh, I'm just honest and to the point.

In general, it is always a good idea to look around at the repository you are contributing to. E.g., formatting of commits messages and how stuff rolls (squash commits or not, rebase before merge, those kinda things).

**Comment by nonsleepr** [comment]
I see what you mean and I respect enforcement of the standard. My point though, that shouldn't be something which is inferred from the commit messages, that stuff should be documented, otherwise, you're requesting others to make their best effort at guessing what you want and if they guessed wrong they would just leave.

I created a follow-up PR #112, which I guess is what you want, but again, I see a lot of emojis in the commits and I'm not sure I would be able to replicate that with my workflow (is that even necessary?).

**Comment by frenck** [comment]
We have multiple contributors to the project, and this issue has not been raised before.

Nevertheless, thanks for your contributions. The add-on is planned for maintenance for the upcoming days anyways.

**Comment by nonsleepr** [comment]
Well, now you closed #112 which addressed your request to break this PR into multiple commits without explanation. There are half-baked #106 and #107 which you hesitated to close. Now I don't understand why aren't my PRs welcomed.
Had there been a proper contributing guide, that would have spared both of us some time.

**Pull request closed without merging**
