### PR TITLE
🚑Fix admin/queries.php for direct users 

### PR DESCRIPTION
**Pull request by sinclairpaul**
# Proposed Changes

Implement sub_filter to rewrite Javascript hardcoding

## Related Issues

#92

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Used the sub_filter method here as well, to be fair my understanding was you could configure Reverse Proxies to follow redirects, which may have been an issue with the Ingress setup.  Just didn't really want to use the sub_filter if possible.

**Comment by frenck** [comment]
Another option is to accept both locations transparently? That would remove the need for redirects as well. To clarify: Both `/` and `/admin` show the same in that case.

**Comment by sinclairpaul** [comment]
The challenge is from my testing, the client has to request /admin for the site to load, so with no redirect it will fail.  I tested using try_files and the paths to the Javascript end up wrong (i.e. for / try /admin/index.php).  I also thought of just throwing a page in root that does a client side redirect, but again would cause the Proxy issue I believe.  Unless I am not following correctly.

**Comment by sinclairpaul** [comment]
Actually I think the penny dropped, new location block for /admin with a different path.  Will test later tonight.

**Comment by sinclairpaul** [comment]
Looked at it, challenge is around then getting the correct fastcgi path in the split out block.  In all honesty the rewrite is the simplest approach.

**Pull request merged**
